---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
  - name: resource-tutorial
 
params:
  GREETING: 

run:
  path: resource-tutorial/scripts/script_hello.sh

